export const ALL_GATE_PASS_POST_REQUEST = 'ALL_GATE_PASS_POST_REQUEST'
export const ALL_GATE_PASS_POST_SUCCESS = 'ALL_GATE_PASS_POST_SUCCESS'
export const ALL_GATE_PASS_POST_FAIL = 'ALL_GATE_PASS_POST_FAIL'

export const SINGLE_GATE_PASS_POST_REQUEST = 'SINGLE_GATE_PASS_POST_REQUEST';
export const SINGLE_GATE_PASS_POST_SUCCESS = 'SINGLE_GATE_PASS_POST_SUCCESS';
export const SINGLE_GATE_PASS_POST_FAIL = 'SINGLE_GATE_PASS_POST_FAIL';

export const CREATE_GATE_PASS_POST_REQUEST = 'CREATE_GATE_PASS_POST_REQUEST';
export const CREATE_GATE_PASS_POST_SUCCESS = 'CREATE_GATE_PASS_POST_SUCCESS';
export const CREATE_GATE_PASS_POST_FAIL = 'CREATE_GATE_PASS_POST_FAIL';

export const UPDATE_GATE_PASS_POST_REQUEST = 'UPDATE_GATE_PASS_POST_REQUEST';
export const UPDATE_GATE_PASS_POST_SUCCESS = 'UPDATE_GATE_PASS_POST_SUCCESS';
export const UPDATE_GATE_PASS_POST_FAIL = 'UPDATE_GATE_PASS_POST_FAIL';

export const DELETE_GATE_PASS_POST_REQUEST = 'DELETE_GATE_PASS_POST_REQUEST';
export const DELETE_GATE_PASS_POST_SUCCESS = 'DELETE_GATE_PASS_POST_SUCCESS';
export const DELETE_GATE_PASS_POST_FAIL = 'DELETE_GATE_PASS_POST_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'